DROP TABLE IF EXISTS Transfers;
DROP TABLE IF EXISTS Withdraws;
DROP TABLE IF EXISTS Deposits;

DROP TABLE IF EXISTS Certificates_of_deposit;


DROP TABLE IF EXISTS CheckingAccounts;
DROP TABLE IF EXISTS InvestmentAccounts;
DROP TABLE IF EXISTS Manages;
--
DROP TABLE IF EXISTS Accounts;
DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Customers;
